"""Compatibility facade for runner implementation modules."""

from __future__ import annotations

from databento_stream_downloader._runner.concurrency import _cancel_futures
from databento_stream_downloader._runner.cost import (
    _allocate_estimated_billable_bytes,
    _allocate_estimated_cost_cents,
    _allocate_estimated_values,
    _check_bucket_cost_caps,
    _check_cost_cap,
    _check_disk_space,
    _cost_ranges,
    _estimate_costs,
    _estimate_range,
    _refuse_ambiguous_zero_cap,
    _total_estimated_cents,
)
from databento_stream_downloader._runner.format import _bytes, _money, _print_costs
from databento_stream_downloader._runner.fsio import (
    _NETWORK_FILESYSTEM_TYPES,
    _TMP_GLOB,
    _TMP_MIN_AGE_SECONDS,
    _exclusive_run_lock,
    _fsync_and_sha256_file,
    _fsync_directory,
    _linux_mount_entries,
    _mount_for_path,
    _nearest_existing_parent,
    _place_tmp,
    _read_sha256_sidecar,
    _record_directory_fsync_skipped,
    _reject_known_network_filesystem,
    _sha256_file,
    _sha256_sidecar_path,
    _sweep_stale_tmp_files,
    _try_lock_file,
    _unlock_file,
    _validate_runtime_config,
    _validate_sha256_sidecar,
    _write_sha256_sidecar,
)
from databento_stream_downloader._runner.ledger import (
    _LEDGER_FILE,
    _print_retry_summary,
    _retry_count_total,
    _retry_counts_by_operation,
    _rotate_ledger_if_needed,
    _universe_semantic_sha256,
    _write_run_ledger,
)
from databento_stream_downloader._runner.lifecycle import (
    _EOF_REFUSAL,
    _NONINTERACTIVE_REFUSAL,
    _run_download,
    _run_download_locked,
    _run_exit_code,
    _utc_now,
    run_download,
    run_download_with_client,
)
from databento_stream_downloader._runner.stream import (
    _deep_validate_cap,
    _stream_missing,
    _stream_one,
)
from databento_stream_downloader._runner.types import (
    DownloaderClient,
    DownloadOutcome,
    WorkItem,
    _DirectoryFsyncTracker,
)
from databento_stream_downloader._runner.validation import (
    _expected_weekdays_after_first_data,
    _raise_on_suspicious_all_no_data,
    _repair_missing_sidecars,
    _repair_one_sidecar,
    _sidecar_needs_repair,
    _sidecar_repair_state,
    _validate,
    _validate_one,
)
from databento_stream_downloader._runner.work import (
    _all_items,
    _cached_items,
    _effective_start,
    _existing_items,
    _sorted_items,
    _total_partitions,
    _warn_if_suspicious_archive_file,
    _warn_suspicious_archive_files,
    _work_items_from_all,
)
from databento_stream_downloader.constants import DATASET

__all__ = [
    "DATASET",
    "_EOF_REFUSAL",
    "_LEDGER_FILE",
    "_NETWORK_FILESYSTEM_TYPES",
    "_NONINTERACTIVE_REFUSAL",
    "_TMP_GLOB",
    "_TMP_MIN_AGE_SECONDS",
    "DownloadOutcome",
    "DownloaderClient",
    "WorkItem",
    "_DirectoryFsyncTracker",
    "_all_items",
    "_allocate_estimated_billable_bytes",
    "_allocate_estimated_cost_cents",
    "_allocate_estimated_values",
    "_bytes",
    "_cached_items",
    "_cancel_futures",
    "_check_bucket_cost_caps",
    "_check_cost_cap",
    "_check_disk_space",
    "_cost_ranges",
    "_deep_validate_cap",
    "_effective_start",
    "_estimate_costs",
    "_estimate_range",
    "_exclusive_run_lock",
    "_existing_items",
    "_expected_weekdays_after_first_data",
    "_fsync_and_sha256_file",
    "_fsync_directory",
    "_linux_mount_entries",
    "_money",
    "_mount_for_path",
    "_nearest_existing_parent",
    "_place_tmp",
    "_print_costs",
    "_print_retry_summary",
    "_raise_on_suspicious_all_no_data",
    "_read_sha256_sidecar",
    "_record_directory_fsync_skipped",
    "_refuse_ambiguous_zero_cap",
    "_reject_known_network_filesystem",
    "_repair_missing_sidecars",
    "_repair_one_sidecar",
    "_retry_count_total",
    "_retry_counts_by_operation",
    "_rotate_ledger_if_needed",
    "_run_download",
    "_run_download_locked",
    "_run_exit_code",
    "_sha256_file",
    "_sha256_sidecar_path",
    "_sidecar_needs_repair",
    "_sidecar_repair_state",
    "_sorted_items",
    "_stream_missing",
    "_stream_one",
    "_sweep_stale_tmp_files",
    "_total_estimated_cents",
    "_total_partitions",
    "_try_lock_file",
    "_universe_semantic_sha256",
    "_unlock_file",
    "_utc_now",
    "_validate",
    "_validate_one",
    "_validate_runtime_config",
    "_validate_sha256_sidecar",
    "_warn_if_suspicious_archive_file",
    "_warn_suspicious_archive_files",
    "_work_items_from_all",
    "_write_run_ledger",
    "_write_sha256_sidecar",
    "run_download",
    "run_download_with_client",
]
